// noinspection UnnecessaryLocalVariableJS

export const JSON_COLORIZER_STRING_KEY = '#7aa2f7';
export const JSON_COLORIZER_STRING_LITERAL = '#9dcc65';
export const JSON_COLORIZER_NUMBER_LITERAL = '#fd914e';
export const JSON_COLORIZER_BOOLEAN_LITERAL = '#9d7cd8';
export const JSON_COLORIZER_NULL_LITERAL = JSON_COLORIZER_BOOLEAN_LITERAL;
export const JSON_COLORIZER_BRACE = '#9abdf5';
export const JSON_COLORIZER_BRACKET = JSON_COLORIZER_BRACE;
export const JSON_COLORIZER_COLON = JSON_COLORIZER_BRACE;
export const JSON_COLORIZER_COMMA = JSON_COLORIZER_BRACE;

export const JSON_COLORIZER_COLORS = {
  STRING_KEY: JSON_COLORIZER_STRING_KEY,
  STRING_LITERAL: JSON_COLORIZER_STRING_LITERAL,
  NUMBER_LITERAL: JSON_COLORIZER_NUMBER_LITERAL,
  BRACE: JSON_COLORIZER_BRACE,
  BRACKET: JSON_COLORIZER_BRACKET,
  COLON: JSON_COLORIZER_COLON,
  COMMA: JSON_COLORIZER_COMMA,
  BOOLEAN_LITERAL: JSON_COLORIZER_BOOLEAN_LITERAL,
  NULL_LITERAL: JSON_COLORIZER_NULL_LITERAL,
};
